spring:
  datasource:
    url: jdbc:h2:mem:sifap;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
